steps:
  - name: "gcr.io/cloud-builders/curl"
    args:
      [
        "-X",
        "POST",
        "-H",
        "Content-type: application/json",
        "--data",
        '{"text":"`vmbackup-sidecar:$_TAG-$SHORT_SHA` build started!"}',
        "${_WEBHOOK_URL}",
      ]
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: sh
    args:
      [
        "-c",
        "docker build -t eu.gcr.io/$PROJECT_ID/vmbackup-sidecar:$(date -u +$_TAG-$SHORT_SHA-%Y%m%d%H%M%S) .",
      ]
  - name: "gcr.io/cloud-builders/curl"
    args:
      [
        "-X",
        "POST",
        "-H",
        "Content-type: application/json",
        "--data",
        '{"text":"`vmbackup-sidecar:$_TAG-$SHORT_SHA` build completed!"}',
        "${_WEBHOOK_URL}",
      ]
substitutions:
  _TAG: $TAG_NAME
images:
  - "eu.gcr.io/$PROJECT_ID/vmbackup-sidecar"
