steps:
  - name: "gcr.io/cloud-builders/curl"
    args:
      [
        "-X",
        "POST",
        "-H",
        "Content-type: application/json",
        "--data",
        '{"text":"`vmbackup-sidecar:latest` build started!"}',
        "${_WEBHOOK_URL}",
      ]
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: sh
    args:
      ["-c", "docker build -t eu.gcr.io/$PROJECT_ID/vmbackup-sidecar:latest"]
  - name: "gcr.io/cloud-builders/curl"
    args:
      [
        "-X",
        "POST",
        "-H",
        "Content-type: application/json",
        "--data",
        '{"text":"`vmbackup-sidecar:latest` build completed!"}',
        "${_WEBHOOK_URL}",
      ]
images:
  - "eu.gcr.io/$PROJECT_ID/vmbackup-sidecar"
